-- MySQL Script generated by MySQL Workbench
-- Tue Feb 24 17:25:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema orders
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orders
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orders` DEFAULT CHARACTER SET utf8 ;
USE `orders` ;

-- -----------------------------------------------------
-- Table `orders`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`Person` (
  `ID` INT NOT NULL,
  `FirstName` VARCHAR(15) NOT NULL,
  `LastName` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`Customers` (
  `ID` INT NOT NULL,
  `House` INT NOT NULL,
  `Street` MEDIUMTEXT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Sex` VARCHAR(10) NULL,
  `BirthDate` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Customers_Person1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Person1`
    FOREIGN KEY (`ID`)
    REFERENCES `orders`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`.`PhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`PhoneNumbers` (
  `PersonID` INT NOT NULL,
  `Number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`PersonID`, `Number`),
  CONSTRAINT `fk_PhoneNumbers_Person1`
    FOREIGN KEY (`PersonID`)
    REFERENCES `orders`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`.`DeliveryAgents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`DeliveryAgents` (
  `ID` INT NOT NULL,
  `DeliveringStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DeliveryAgents_Person1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_DeliveryAgents_Person1`
    FOREIGN KEY (`ID`)
    REFERENCES `orders`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`Orders` (
  `ID` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `PaymentMethod` VARCHAR(45) NULL,
  `TotalPrice` DOUBLE NOT NULL,
  `SerialNumber` INT ZEROFILL NOT NULL,
  `RegisterationDate` DATE NULL,
  `ShippingDate` DATE NULL,
  `DeliveringDate` DATE NULL,
  `CustomersID` INT NOT NULL,
  `DeliveryAgentsID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Orders_DeliveryAgents1_idx` (`DeliveryAgentsID` ASC) VISIBLE,
  INDEX `fk_Orders_Customers1_idx` (`CustomersID` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_DeliveryAgents1`
    FOREIGN KEY (`DeliveryAgentsID`)
    REFERENCES `orders`.`DeliveryAgents` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`CustomersID`)
    REFERENCES `orders`.`Customers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`Items` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` MEDIUMTEXT NOT NULL,
  `Category` VARCHAR(25) NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`.`Coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`Coupons` (
  `ID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Value` INT NOT NULL,
  `Code` VARCHAR(45) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `CustomersID` INT NOT NULL,
  INDEX `fk_Coupons_Customers1_idx` (`CustomersID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Coupons_Customers1`
    FOREIGN KEY (`CustomersID`)
    REFERENCES `orders`.`Customers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`.`OrderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders`.`OrderItems` (
  `OrdersID` INT NOT NULL,
  `ItemsID` INT NOT NULL,
  `Product` VARCHAR(45) NOT NULL,
  `Amount` INT NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`OrdersID`, `ItemsID`),
  INDEX `fk_Orders_has_Items_Items1_idx` (`ItemsID` ASC) VISIBLE,
  INDEX `fk_Orders_has_Items_Orders1_idx` (`OrdersID` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_has_Items_Orders1`
    FOREIGN KEY (`OrdersID`)
    REFERENCES `orders`.`Orders` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Items_Items1`
    FOREIGN KEY (`ItemsID`)
    REFERENCES `orders`.`Items` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
